import { z } from "zod"

export const SeanceSchema = z.object({
    id: z.string(),
    animal_id: z.string(),
    date: z.string(),
    images_ulrs: z.string().nullable(),
    mesure_ant_droite_apres: z.number().nullable(),
    mesure_ant_droite_avant: z.number().nullable(),
    mesure_ant_gauche_apres: z.number().nullable(),
    mesure_ant_gauche_avant: z.number().nullable(),
    mesure_post_droite_apres: z.number().nullable(),
    mesure_post_droite_avant: z.number().nullable(),
    mesure_post_gauche_apres: z.number().nullable(),
    mesure_post_gauche_avant: z.number().nullable(),
    motif: z.string().nullable(),
    notes_admin: z.string().nullable(),
    observations: z.string().nullable(),
    recommandations: z.string().nullable(),
    suivi: z.string().nullable(),
    type: z.string().nullable(),
})

export const InsertSeanceSchema = z.object({
    id: z.string().optional(),
    animal_id: z.string(),
    date: z.string(),
    images_ulrs: z.string().nullable().optional(),
    mesure_ant_droite_apres: z.number().nullable().optional(),
    mesure_ant_droite_avant: z.number().nullable().optional(),
    mesure_ant_gauche_apres: z.number().nullable().optional(),
    mesure_ant_gauche_avant: z.number().nullable().optional(),
    mesure_post_droite_apres: z.number().nullable().optional(),
    mesure_post_droite_avant: z.number().nullable().optional(),
    mesure_post_gauche_apres: z.number().nullable().optional(),
    mesure_post_gauche_avant: z.number().nullable().optional(),
    motif: z.string().nullable().optional(),
    notes_admin: z.string().nullable().optional(),
    observations: z.string().nullable().optional(),
    recommandations: z.string().nullable().optional(),
    suivi: z.string().nullable().optional(),
    type: z.string().nullable().optional(),
})

export const UpdateSeanceSchema = z.object({
    id: z.string().optional(),
    animal_id: z.string().optional(),
    date: z.string().optional(),
    images_ulrs: z.string().nullable().optional(),
    mesure_ant_droite_apres: z.number().nullable().optional(),
    mesure_ant_droite_avant: z.number().nullable().optional(),
    mesure_ant_gauche_apres: z.number().nullable().optional(),
    mesure_ant_gauche_avant: z.number().nullable().optional(),
    mesure_post_droite_apres: z.number().nullable().optional(),
    mesure_post_droite_avant: z.number().nullable().optional(),
    mesure_post_gauche_apres: z.number().nullable().optional(),
    mesure_post_gauche_avant: z.number().nullable().optional(),
    motif: z.string().nullable().optional(),
    notes_admin: z.string().nullable().optional(),
    observations: z.string().nullable().optional(),
    recommandations: z.string().nullable().optional(),
    suivi: z.string().nullable().optional(),
    type: z.string().nullable().optional(),
})